### ISSUE TITLE
代码阅读起来不流畅

### ISSUE THREAD

**Issue by charlesfufu** [baiyyang/medical-entity-recognition#2]
方法定义太多了吧，好好的tensorflow被你拆的这里调一个方法那里调一个方法。两句话写个方法，不方便debug。可读性太差了

**Comment by baiyyang** [comment]
。。。。嗯，当时对tensorflow不太熟，也是一边摸索，一边学习，一边coding，过阵子重新写一遍，方便大家理解，感谢批评。

**Comment by fanw52** [comment]
您好，想请教您一个问题，在预测的时候需要变量transition_param,而这个变量是由crf_log_likelihood接口得到的，该接口需要传入参数包括lable,可是在测试的时候是没有label的呀，请指教 @baiyyang

**Comment by baiyyang** [comment]
测试就是为了得到label。。。所有不会有label。。
