### ISSUE TITLE
你好，请问word2id.pkl怎么生成的

### ISSUE THREAD

**Issue by highinsky** [baiyyang/medical-entity-recognition#3]
你好，请问word2id.pkl怎么生成的

**Comment by baiyyang** [comment]
你好，
       .pkl文件是使用python的pickle库生成的，pickle.dump()，把一个对象持久化。




| |
baiyyang
|
|
baiyyang@163.com
|


在2018年11月6日 17:41，highinsky<notifications@github.com> 写道：

你好，请问word2id.pkl怎么生成的
