### ISSUE TITLE
请问crf_unit.py如何char模型

### ISSUE THREAD

**Issue by bluesky632** [baiyyang/medical-entity-recognition#4]
您好，我想用crf训练基于字的命名实体识别，我在crf_unit.py里能正常运行训练基于词的模型，但是基于字的模型，出来的结果不对，这是我哪个地方改错了吗？
![20181121165024](https://user-images.githubusercontent.com/22184743/48829632-b107be80-edad-11e8-82fb-d924c0f88f1e.png)

**Comment by baiyyang** [comment]
使用以字为单元crf训练，需要变动相关特征，比如字的话，可能不需要分词，词性特征需要去除，同时可以增加特征，如是否是数字，中文，英文等，祝好。
