### ISSUE TITLE
请问如何对您训练的crf模型进行测试？

### ISSUE THREAD

**Issue by FallingSlowly** [baiyyang/medical-entity-recognition#6]
如题，可以用您提供的命令行对BLISTM-CRF进行测试，但是不知道如何测试CRF
非常感谢！

**Comment by baiyyang** [comment]
Hi，你可以直接进入crf文件夹，使用python crf_unit.py命令运行

**Comment by Licko0909** [comment]
> 如题，可以用您提供的命令行对BLISTM-CRF进行测试，但是不知道如何测试CRF
> 非常感谢！

我刚刚修改了一下，可以用了。主要对crf_unit.py做了以下几个修改：

1、将crt.predata批量修改为predata
2、填入作者给的两个训练和测试文件
testpath = '../train_test_data/test_bio_word.txt'
trainpath = '../train_test_data/train_bio_word.txt'

![image](https://user-images.githubusercontent.com/27897166/64329793-6684c500-d002-11e9-8292-e9836eccf5e3.png)

![image](https://user-images.githubusercontent.com/27897166/64329596-1c034880-d002-11e9-9d61-06221b395625.png)

**Comment by LCQ940818** [comment]
请问crf_unit.py里面的import zhon.hanzi as zh从何而来，我是初学者，想先跑通代码，在学习代码
